name: SkyBlockExpansion
version: '${version}'
main: club.blocklife.touch.skyblockexpansion.SkyBlockExpansion
api-version: '1.20'
softdepend: [PlaceholderAPI]
commands:
  tpa:
    description: tpa
  tpaccept:
    description: tpaccept
  tpadeny:
    description: tpadeny
  hat:
    description: hat
  showitem:
    description: ShowItem
    aliases: i
  seeinv:
    description: seeinv
  LookPlayer:
    description: 查看玩家
permissions:
  LookPlayer.use:
    description: 允许使用查看玩家
    default: true
  LookPlayer.Interact:
    description: 允许玩家交互
    default: true
  LookPlayer.Admin:
    description: 允许使用/LookPlayer
    default: op